### PR TITLE
(feat) Add support for Capacitor

### LINKED ISSUE #168: Capacitor support for SSL pinning
The plugin currently doesn't play nicely together with [capacitor](https://capacitor.ionicframework.com) which is the successor for Cordova. The following was experienced while developing for iOS.

While the plugin generally work as expected, it breaks on certificate pinning. The problem lies in a changed project structure within xCode and therefor the resulting iOS App. Due to the changes the plugin doesn't have access to users files right of the bat.

At the moment there is a hard-coded requirement to provide certificates within the `www/certificates` folder. New Capacitor applications don't have this folder anymore. They have a public folder. By updating the angular.json one can compile certificates into Angulars www folder which then lands them in `public/certificates` in the xCode project. The only trouble being that the advanced-http plugin doesn't have access to this folder. At least not by default.

This is probably an issue with access rights needing setup within the xCode project. A similar issue might apply to Android.

### PR DESCRIPTION
**Pull request by dtarnawsky**
The resolves #168 by searching for certificates in both the www (Cordova) and public folder (Capacitor).

### CODE REVIEW

**Comment by dtarnawsky** [comment]
The PR allows you to put certificates in either the public or www folders but I've seen that it's been requested to only choose one by the plugin detecting if you are in Capacitor or Cordova. I don't have a lot of time to refactor the PR but I could reopen the PR if it is likely to be merged as is.

**Review by SowmyaFyle — COMMENTED** [review]
noice

**Comment by jonesdhtx** [comment]
Can you provide link or explanation about PR being closed? Was it merged or ?

**Comment by dtarnawsky** [comment]
It looks like support was added for Capacitor in main: [see code](https://github.com/silkimen/cordova-plugin-advanced-http/blob/60c042164a5c4c66f73823c0d016c8a3a4dd136f/src/android/com/silkimen/cordovahttp/CordovaServerTrust.java#L91)

Not sure if this has been released yet though.

**Pull request closed without merging**
