### PR TITLE
Support for browser file upload

### PR DESCRIPTION
**Pull request by Kepro**
just send FormData if it's an instance of FormData already

### CODE REVIEW

**Comment by Kepro** [comment]
Hey, @silkimen should I extend my PR for something more? this PR is one thing that is missing to can work like normal people also from browser :D

**Comment by Kepro** [comment]
Hi @silkimen well in February, when you upload a file from browser it always sends an empty request, probably it was fixed already after months

**Comment by silkimen** [comment]
Do you mean [`uploadFile()`](https://github.com/silkimen/cordova-plugin-advanced-http#uploadfile)? Or multipart requests with FormData? I don't think that your problem is already fixed, but I need to understand it. Please add some example code to reproduce the problem.

**Comment by Kepro** [comment]
no, regular "sendRequest" with POST + FormData was sending empty request from web(works fine on iOS) back in February...

**Pull request closed without merging**
