### PR TITLE
options.data is being set to null where previously it was undefined

### PR DESCRIPTION
**Pull request by JamieMcDonnell**
By setting options.data to null, then checking it's validity in processData, it is being considered invalid causing the request to fail:
```javascript
switch (options.method) {
      case 'post':
      case 'put':
      case 'patch':
        return helpers.processData(options.data, options.serializer, function(data) {
          exec(onSuccess, onFail, 'CordovaHttpPlugin', options.method, [url, data, options.serializer, headers, options.timeout, options.followRedirect, options.responseType]);
        });
...
```

If the options.data property is undefined, it has not been provided, therefore it should not be set to null - please correct this.

### CODE REVIEW

**Comment by silkimen** [comment]
Which problem do you try to solve exactly? Please provide some more info.

**Comment by JamieMcDonnell** [comment]
I am trying to send a simple PUT request that contains no data, only a url.
The options.data property is being set to null (because it is reported as
undefined) and null is not one of the accepted data types (Array/Object) so
the request gets rejected.
I am unable to provide code samples until monday, but does this give you
enough info to work with?
Thanks so much ;)
Jamie

**Comment by JamieMcDonnell** [comment]
Hi Silkimen, apologies for my delaying sending you this example - it was a busy weekend ;)

This simple PUT request fails because options.data is null:
```javascript
let url = 'path/to/my/rest/api'
let requestOptions = {
    method: 'PUT'
}

cordova.plugin.http.useBasicAuth(username, password)
cordova.plugin.http.setDataSerializer('json')
cordova.plugin.http.setRequestTimeout(5.0)

cordova.plugin.http.sendRequest(url, requestOptions, function (response) {
          console.log('Success: ', response)
        }, function (response) {
          console.log('Error: ', response)
})
```

I hope this is all you need to resolve this use-case? Thanks a lot and have a great festive season ;)

**Comment by JamieMcDonnell** [comment]
Hi Sefa, sorry to seem pushy, but do you have a rough idea when you might get to solving this bug? My client is waiting on me to push a bunch of changes that rely on PUT requests working. I understand you are no doubt busy as we all are, but a rough ETA would be wonderful ;) Thanks so much.

**Comment by silkimen** [comment]
Hi Jamie, I'll have some time to check it this weekend. Actually, I don't remember why I've added this line, I'll need to check if it impacts another feature. But I do remember that `data` was meant to be a mandatory option. So I don't understand how it's working when you change this line and leave it undefined. 🤔

**Comment by JamieMcDonnell** [comment]
Hi Sefa,
that's great, thanks! Why should data be a mandatory option? PUT requests
can carry the data in the URL, which is how all of the requests I make to
our APIs which do not need a data object payload work.

I have modified my pull request, and so the pressure is off for me now for
this bug, as PUT requests are now working. My other request, allowing a
String value in POST requests would be very helpful though if you have time
to prioritise that one?

Thanks again!

Jamie

**Comment by JamieMcDonnell** [comment]
Yes, json serializer. Passing an empty object as data is enough for the
request not to fail.
Thanks

**Comment by silkimen** [comment]
Hmm, ok. But sending an empty object will send following serialized content `{}` in the body.

If you want to send an EMPTY body instead, it's not possible with `json` serializer. The reason is that an empty string is not a valid JSON value, [see ECMA specs for details](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf). And `undefined` is neither (it's valid JavaScript but not valid JSON), whereas `null` is allowed.

But unfortunately, it's not supported by Apple's NSJSONSerialization class, see [Apple Developer documentation for `dataWithJSONObject:options:error:`](https://developer.apple.com/documentation/foundation/nsjsonserialization/1413636-datawithjsonobject?language=objc). The parameter `obj` is described as "The object from which to generate JSON data. Must not be nil.".

Therefore, it's working as intended. Your PR will cause more problems than it will help. If you want to send an empty body, I'll recommend you to use the `utf8` serializer and pass an empty string as data.

**Pull request closed without merging**
