### PR TITLE
feature: added x509 authentication for iOS and android

### PR DESCRIPTION
**Pull request by nekator**
The goal of this pull request is to bring X509 client authentication into cordova http after https://github.com/sneas/cordova-HTTP2 was marked as deprecated.

This PR also contains a bug fix for x509 authentication on iOS, which was present in https://github.com/sneas/cordova-HTTP2

### CODE REVIEW

**Comment by nekator** [comment]
@silkimen maybe you can help me to understand why the CI-build fails?

**Comment by silkimen** [comment]
Hi nekator, thanks for your PR! I think there is something broken in my CI setup. 😣 I'll need to check that. 🤔

**Comment by nekator** [comment]
@silkimen i was so blind...   https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions. This is exactly the problem and it is mentioned in the logs... 

So how do we deal with it?

**Comment by silkimen** [comment]
Hi Heiko,
sorry, for my late response. Unfortunately, I am very busy atm. Yes, you're right, that's the problem. I'll pull your changes on my local dev machine and test them when I find some time.

**Comment by nekator** [comment]
Hi @silkimen, did you already had time to test my changes? Is there something i can do to support your test?

**Comment by danielsogl** [comment]
https://github.com/ionic-team/ionic-native/pull/2247

**Comment by nekator** [comment]
I am going to merge the current master branch this week and then I will start writing test for this feature. So maybe next week there will be a complete pr. 😁

**Comment by nekator** [comment]
@silkimen 
I think i'm done.

Could you take a look at it?

**Comment by silkimen** [comment]
Hi Heiko, I tried to run the tests, but atm they are all failing. I'll check what's going wrong the next days. I've also sent you an invitation for my Slack channel, so we can write there to fix the problem.

**Comment by smashleon23** [comment]
Hi guys, I am trying to use this PR in a Ionic project, I am using the plugin without native HTTP to authenticate with a client certificate, but after the call to cordova.plugin.http.setX509AuthClientCredentials I don't see neither success nor fail callback return, the last clue that I saw in Logcat was CordovaHttpPlugin.setX509AuthClientCredentials blocked the main thread for 612ms. Plugin should use CordovaInterface.getThreadPool(). Do you have any suggestion?

I am doing this inside this.platform.ready:
```
       this.file.readAsArrayBuffer(this.file.applicationDirectory + "www/assets/certs", "cert.p12").then(certContents => {
         console.log("Before loading certificate!");
         cordova.plugin.http.setX509AuthClientCredentials(certContents, "XXXX", () => console.log("AUTHENTICATION SUCCESSFUL"), error => console.log("AUTHENTICATION FAILED"));
       }).catch(error => console.log("Error reading certificate" + error.message));
```

**Comment by silkimen** [comment]
@smashleon23 Please do not use this PR because it's not ready for public usage. It has some security flaws and functionality is also partly broken.

**Comment by smashleon23** [comment]
@silkimen Thanks for your answer, I will be looking forward to hear about this PR because that  would be an awesome feature to have.

**Comment by gtmn** [comment]
Haven't looked too much into the code itself yet.
@silkimen could you maybe elaborate a bit more on your insights on this feature?

**Comment by evyatarkanety** [comment]
@silkimen - What is estimation for release this feature?

**Comment by silkimen** [comment]
@evyatarkanety atm, there is no estimation for this feature. It's a security related feature and therefore I don't want to rush about.

Actually, the android implementation is already implemented and also shipped in current versions. But I've not documented the feature because it's not ready yet for iOS. It's possible that I'll need to change the API.

If you still want to use it for android check these lines in e2e specs: [test/e2e-specs.js#L25-L32](https://github.com/silkimen/cordova-plugin-advanced-http/blob/master/test/e2e-specs.js#L25-L32 ) and [test/e2e-specs.js#L895-L904](https://github.com/silkimen/cordova-plugin-advanced-http/blob/master/test/e2e-specs.js#L895-L904).

**Comment by silkimen** [comment]
Closing this, because this feature was implemented in v2.5.0 inspired by this PR. Thank you @nekator! ✌️ See [README.md#setclientauthmode](https://github.com/silkimen/cordova-plugin-advanced-http#setclientauthmode).

**Comment by nekator** [comment]
@silkimen awesome.  I'm  sorry that I couldn't finish this off.

**Pull request closed without merging**
