### PR TITLE
Allow empty response body even though responseType is set

### PR DESCRIPTION
**Pull request by antikalk**
This pull request only parses the response data if the response data is set. This allows a 200 SUCCESS api response to be successful even though the response body is empty and the responseType is set.

Related to issue #334

### CODE REVIEW

**Comment by silkimen** [comment]
Hi antikalk, this one looks good, but I prefer early return pattern (see https://www.freecodecamp.org/forum/t/the-return-early-pattern-explained-with-javascript-examples/19364). Therefore I'd rather add following in line 294:

```js
if (!response.data) {
  return success(response);
}
```

And would you mind writing a test case for #334? Check out [test/e2e-specs.js](https://github.com/silkimen/cordova-plugin-advanced-http/blob/master/test/e2e-specs.js) to see how the are built. I do mention the issue number in the description.

**Comment by antikalk** [comment]
I switched to the early return pattern and set the response data to null if it is not set.

`javascript
if (!response.data) {
  // return null as data if response data is not set
  response.data = null;
  return success(response);
}`

I also added some tests to the js-specs.js.

Unfortunately I don't see any HTTP endpoint at httpbin.org that returns an empty body. Therefor I am currently not able to add a new e2e test for testing empty body responses...

**Comment by silkimen** [comment]
You can use `https://httpbin.org/status/200` for an empty response body.

**Comment by antikalk** [comment]
I added an e2e test, that checks whether a 200 OK response with an empty response body gets resolved.

**Comment by silkimen** [comment]
Hi antikalk, thank you. Unfortunately, I had no chance to check your specs, but I hope I'll have same time this weekend. Just being curious, why did you revert your commit, that's returning `null` when the body is empty?

**Comment by antikalk** [comment]
I am still unsure if manipulating the response data in that way could cause some application using the plugin to break. My guess is that that would be very unlikely and that returning null if the response data is empty would be more consistent. What do you think? I could change it back if you want.

**Comment by silkimen** [comment]
Okay, I see. I also think that it'd be more consistent returning null. For following reasons:
* old versions don't support empty responses, they will call the fail callback with an empty string ==> should not break anything with existing apps
* returning an empty string in the success callback (which it would) is probably not a good idea when people are expecting an ArrayBuffer or Blob ==> therefore making the response type `Nullable<ArrayBuffer>`or `Nullable<Blob>` seems to be the more consistent solution

**Comment by antikalk** [comment]
Thank you for your response. I just reverted commit bfc6ba2.

**Comment by silkimen** [comment]
Thanks for your PR! 😀👍

**Comment by silkimen** [comment]
I've fixed your e2e spec here: https://github.com/silkimen/cordova-plugin-advanced-http/commits/antikalk-master

But there is still a problem breaking test case "35: should return empty body string correctly (GET)".

**Pull request merged**
