### PR TITLE
utf-8 encoded string serializer

### PR DESCRIPTION
**Pull request by robertocapuano**
Added a "raw" serializer to be able to send XML document.

var http = ...
var url = ...
var headers = {};

http.setDataSerializer('raw');
var body = "<document></document>";

http.post(url,body, headers );

### CODE REVIEW

**Comment by chax** [comment]
I really need this fix. Can you review it and merge it @silkimen ?

**Comment by silkimen** [comment]
Hi guys,
I've just checked this PR (at least the iOS implementation), but I don't see a "raw" serializer here. It's not applicable for transmitting e.g. an ArrayBuffer object. I will rename it to "text" serializer, adding a default header "text/plain; charset=utf-8" (which you can override by specifying custom header). @robertocapuano I think this is what your code does, right?

And another problem I see here is this line: [AFURLRequestSerialization.m L1234](https://github.com/robertocapuano/cordova-plugin-advanced-http/blob/master/src/ios/AFNetworking/AFURLRequestSerialization.m#L1234). You are assuming the parameters object is a NSString, right? But it's meant to be a NSDictionary, you can see here in [CordovaHttpPlugin.m L154](https://github.com/robertocapuano/cordova-plugin-advanced-http/blob/master/src/ios/CordovaHttpPlugin.m#L154).

So, before merging this I'll need to:
- change the interface allowing Strings to be passed
- add some tests

@robertocapuano Please feel free to correct me, if I'm wrong with your code.

**Comment by robertocapuano** [comment]
Hi @silkimen,
About the serialization logic, you're correct, the rationale of the change is to transmit text content, e.g.: xml document.
The interface AFHTTPSessionManager needs a NSDictionary for parameters, but requestBySerializingRequest uses a generic type (id) as type, and there I speculate to use NSString without problems.

--
roberto

**Comment by chax** [comment]
I had some problems using your fork @robertocapuano when doing POST requests with empty body (sending as empty string ""), so this might be the issue @silkimen is talking about, accepting only NSDictionary.
@silkimen, yes i think you must change your interface to accept Strings also.

**Comment by chax** [comment]
Android version is working fine because it accepts Object as type (Object is superclass of String, so the method .toString() works without problems there).

**Comment by chax** [comment]
Also i wouldn't add any default *Content-type* headers, because this should be *raw*, meaning no automatic manipulation of requests nor responses, just sending it as it is and receiving it as it is. Users will add headers themselves if they need them.

**Comment by silkimen** [comment]
@chax You're right, if it comes to a _raw_ serializer, but this implementation isn't. It's sending data encoded as UTF-8 string (see [AFURLRequestSerialization.m#L1234](https://github.com/robertocapuano/cordova-plugin-advanced-http/blob/master/src/ios/AFNetworking/AFURLRequestSerialization.m#L1234)). That's the reason I want to add a default content type.
You'd need to implement a serializer capable of handling ArrayBuffers to be able to send raw data, so you could also send e.g. binary files.

**Comment by chax** [comment]
Raw, in a broader sense of the word means unprocessed. So, yeah, if you could make changes so that your interface accepts whatever as request data (body).
So that if user sends string, request is made with utf8 encoded (default encoding) string.
And if user sends ArrayBuffer that you send binary data as request body, etc.
That would be actual raw (generic) serializer, and that would be exactly what people need, because it would covered all the other cases where one would not want to use any type of automatic serialization of requests and responses.

**Comment by chax** [comment]
Ok, I might be asking too much here, but, to finish this discussion, if you don't like name raw (because it's to wide in what it means), this should probably be renamed to text, leave it as it is (UTF8 string encoding and all...), just make small change of accepting NSObject as request data (just like Android implementation accepts Object superclass), so that it can be serialized in whatever way you need (depending on serializer).

**Comment by chax** [comment]
Any news on this?

**Comment by mgmanoj** [comment]
waiting for you guys.Please do an update on above @robertocapuano @silkimen @chax .Thank you all

**Comment by chax** [comment]
Thanks for merging this @silkimen and for making release 1.10.0

**Comment by silkimen** [comment]
You're welcome! Hope this will fit your needs! 🙂

**Comment by mgmanoj** [comment]
my understanding is that setting data serializer to utf8 will post the data body without any encoding but getting url encoded post body .Please have a look at my code below

   post(postparams,type) {

      let headers = { "Content-type": "text/xml",}; 
        
        this.http.setDataSerializer('utf8'); 

        let postData = 
            this.http.post(this.postUrlConstructor(postparams,type),this.postBodyConstructor(postparams,type),headers)
            .then(response => JSON.parse(response.data));

        return Observable
            .fromPromise(postData)
            .map(function(results){ return results; })
            .catch(function(error){
                return Observable.throw(new Error(" Error posting " + ": " + error.status + " => " + error.message));
            });
    }`

**Comment by silkimen** [comment]
@mgmanoj: can you please set a breakpoint at [helpers.js#L69](https://github.com/silkimen/cordova-plugin-advanced-http/blob/master/www/helpers.js#L69) and then run `this.http.setDataSerializer('utf8')`? Does the function return "utf8" or something else?

**Comment by mgmanoj** [comment]
@silkimen : Iam working on a Ios app using prestashop API which only accepts xml data for post/put requests.My issue is even after setting dataserializer to 'utf8', the xml string of post body is encoding.
what to do to make the request without any encoding?

**Pull request merged**
