### PR TITLE
iOS: App crashes on error if body is empty

### PR DESCRIPTION
**Pull request by troyanskiy**
Prevent crash if body does not exist on error

### CODE REVIEW

**Comment by silkimen** [comment]
Hmm ok, that's interesting. Actually, it shouldn't be null if there is a response. Do you have an example service I can check against to see what's going wrong?

**Comment by troyanskiy** [comment]
I don’t have open example service, it’s just error 401 without any body
when file download.

**Comment by silkimen** [comment]
Ok thanks, I'll check that!

**Comment by troyanskiy** [comment]
Thanks a lot!

**Comment by silkimen** [comment]
Ok, found it, you are right. This is a edge case only occurring during "downloadFile" operation, because it's the only one not using "TextResponseSerializer". I'll add a description (so it matches Android behavior) and a test case.

**Pull request merged**
